name = "Majestic-trading-  -bot"

main = "src/index.js"
compatibility_date = "2022-11-30"


[vars]
NGROK_TOKEN = "2gKpXAO0hMuwy7jo8uYihx3vf9s_5BahUMC3DLA4PaEaiVZ9Y"
CHART_IMG_API_KEY = "Tx6cM77ZgO5PMujVQRkAW1ZKgAzqW1i08GVFoMEC"
TELEGRAM_API_TOKEN = "6705414688:AAHw3b91WkJX1ZfT6LijMk-ot1p6DTNg8ZI"
TELEGRAM_SECRET_TOKEN = "MajesticCryptoTrading2024"